# Site settings
name: Olivier Moitroux
description: "Belgian engineer in computer sciences, Junior Entrepreneur at free time, ai/tech dreamer and enthusiastic diver."
url: "www.cloud.moitroux.com"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  OlivierMoitroux
linkedin_username: olivier-moitroux
#flickr_username: 155871750@N05/
#medium_username:  olivier.moitroux
blog_url: "/blog"
email: olivier.moitroux@gmail.com

resume_url: "https://www.cloud.moitroux.com/s/rrn8eGF2XjDF2yn"


#instagram_username:  your_instagram_username_goes_here
#codepen_username: your_codepen_username_goes_here
#facebook_username: your_facebook_username_goes_here
#vk_username: your_vk_username_goes_here
#twitter_username: your_twitter_username_goes_here
#google_plus_username: your_google_plus_username_goes_here
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#lastfm_username: your_lastfm_username_goes_here
#steam_username: your_steam_username_goes_here
#soundcloud_username:  your_soundcloud_username_goes_here
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#vine_username:  your_vine_username_goes_here
#reddit_username: your_reddit_username_goes_here


avatar: yes
# avatar_img_path: "imgs/pacman.png""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars.githubusercontent.com/OlivierMoitroux"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
